DELETE FROM CCCompany WHERE 1=1;

INSERT INTO CCCompany(companyName, prefix, len) VALUES ('American Express', 34, 15);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('American Express', 37, 15);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Bankcard', 5610, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Bankcard', 560221, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Bankcard', 560222, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Bankcard', 560223, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Bankcard', 560224, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Bankcard', 560225, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('China UnionPay', 62, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club Carte Blanche', 300, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club Carte Blanche', 301, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club Carte Blanche', 302, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club Carte Blanche', 303, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club Carte Blanche', 304, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club Carte Blanche', 305, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 300, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 301, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 302, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 303, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 304, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 305, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 309, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 36, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 38, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Diners Club International', 39, 14);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 6011, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 622126, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 622925, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 644, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 645, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 646, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 647, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 648, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 649, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Discover Card', 65, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('InterPayment', 636, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3528, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3529, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3530, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3531, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3532, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3533, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3534, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3535, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3536, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3537, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3538, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3539, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3540, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('JCB', 3589, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Laser', 6304, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Laser', 6706, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Laser', 6771, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Laser', 6709, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2221, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2222, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2223, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2224, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2225, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2226, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2227, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2228, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2719, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 2720, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 51, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 52, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 53, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 54, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('MasterCard', 55, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Solo', 6334, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Solo', 6767, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 4903, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 4905, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 4911, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 4936, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 564182, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 633110, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 6333, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Switch', 6759, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Visa', 4, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('UATP', 1, 15);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 506099, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 506198, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 650002, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 650003, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 650004, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 650019, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 650025, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 650026, 16);
INSERT INTO CCCompany(companyName, prefix, len) VALUES ('Verve', 650027, 16);

-- COUNT = 90
SELECT COUNT(90) FROM CCCompany;
