DELETE FROM "CountryRace" WHERE 1=1;
INSERT INTO "CountryRace" VALUES (1, 'AUS', '4');
INSERT INTO "CountryRace" VALUES (2, 'AUS', '5');
INSERT INTO "CountryRace" VALUES (3, 'AUS', '6');
INSERT INTO "CountryRace" VALUES (4, 'CAN', '4');
INSERT INTO "CountryRace" VALUES (5, 'CAN', '5');
INSERT INTO "CountryRace" VALUES (6, 'CAN', '6');
INSERT INTO "CountryRace" VALUES (7, 'HKG', '1');
INSERT INTO "CountryRace" VALUES (8, 'HKG', '2');
INSERT INTO "CountryRace" VALUES (9, 'HKG', '4');
INSERT INTO "CountryRace" VALUES (10, 'MYS', '1');
INSERT INTO "CountryRace" VALUES (11, 'MYS', '2');
INSERT INTO "CountryRace" VALUES (12, 'MYS', '3');
INSERT INTO "CountryRace" VALUES (13, 'PHL', '3');
INSERT INTO "CountryRace" VALUES (14, 'PHL', '4');
INSERT INTO "CountryRace" VALUES (15, 'PHL', '6');
INSERT INTO "CountryRace" VALUES (16, 'SGP', '1');
INSERT INTO "CountryRace" VALUES (17, 'SGP', '2');
INSERT INTO "CountryRace" VALUES (18, 'SGP', '3');
INSERT INTO "CountryRace" VALUES (19, 'THA', '1');
INSERT INTO "CountryRace" VALUES (20, 'THA', '2');
INSERT INTO "CountryRace" VALUES (21, 'THA', '3');
INSERT INTO "CountryRace" VALUES (22, 'GBR', '2');
INSERT INTO "CountryRace" VALUES (23, 'GBR', '4');
INSERT INTO "CountryRace" VALUES (24, 'GBR', '6');
INSERT INTO "CountryRace" VALUES (25, 'USA', '4');
INSERT INTO "CountryRace" VALUES (26, 'USA', '5');
INSERT INTO "CountryRace" VALUES (27, 'USA', '6');

-- COUNT = 26
SELECT COUNT(1) FROM "CountryRace";