DELETE FROM "Country" WHERE 1=1;

INSERT INTO "Country" VALUES ('AFG', 'Afghanistan');
INSERT INTO "Country" VALUES ('ALB', 'Albania');
INSERT INTO "Country" VALUES ('DZA', 'Algeria');
INSERT INTO "Country" VALUES ('ASM', 'American Samoa');
INSERT INTO "Country" VALUES ('AND', 'Andorra');
INSERT INTO "Country" VALUES ('AGO', 'Angola');
INSERT INTO "Country" VALUES ('AIA', 'Anguilla');
INSERT INTO "Country" VALUES ('ATA', 'Antarctica');
INSERT INTO "Country" VALUES ('ATG', 'Antigua and Barbuda');
INSERT INTO "Country" VALUES ('ARG', 'Argentina');
INSERT INTO "Country" VALUES ('ARM', 'Armenia');
INSERT INTO "Country" VALUES ('ABW', 'Aruba');
INSERT INTO "Country" VALUES ('AUS', 'Australia');
INSERT INTO "Country" VALUES ('AUT', 'Austria');
INSERT INTO "Country" VALUES ('AZE', 'Azerbaijan');
INSERT INTO "Country" VALUES ('BHS', 'Bahamas');
INSERT INTO "Country" VALUES ('BHR', 'Bahrain');
INSERT INTO "Country" VALUES ('BGD', 'Bangladesh');
INSERT INTO "Country" VALUES ('BRB', 'Barbados');
INSERT INTO "Country" VALUES ('BLR', 'Belarus');
INSERT INTO "Country" VALUES ('BEL', 'Belgium');
INSERT INTO "Country" VALUES ('BLZ', 'Belize');
INSERT INTO "Country" VALUES ('BEN', 'Benin');
INSERT INTO "Country" VALUES ('BMU', 'Bermuda');
INSERT INTO "Country" VALUES ('BTN', 'Bhutan');
INSERT INTO "Country" VALUES ('BOL', 'Bolivia');
INSERT INTO "Country" VALUES ('BIH', 'Bosnia and Herzegovina');
INSERT INTO "Country" VALUES ('BWA', 'Botswana');
INSERT INTO "Country" VALUES ('BRA', 'Brazil');
INSERT INTO "Country" VALUES ('IOT', 'British Indian Ocean Territory');
INSERT INTO "Country" VALUES ('VGB', 'British Virgin Islands');
INSERT INTO "Country" VALUES ('BRN', 'Brunei');
INSERT INTO "Country" VALUES ('BGR', 'Bulgaria');
INSERT INTO "Country" VALUES ('BFA', 'Burkina Faso');
INSERT INTO "Country" VALUES ('BDI', 'Burundi');
INSERT INTO "Country" VALUES ('KHM', 'Cambodia');
INSERT INTO "Country" VALUES ('CMR', 'Cameroon');
INSERT INTO "Country" VALUES ('CAN', 'Canada');
INSERT INTO "Country" VALUES ('CPV', 'Cape Verde');
INSERT INTO "Country" VALUES ('CYM', 'Cayman Islands');
INSERT INTO "Country" VALUES ('CAF', 'Central African Republic');
INSERT INTO "Country" VALUES ('TCD', 'Chad');
INSERT INTO "Country" VALUES ('CHL', 'Chile');
INSERT INTO "Country" VALUES ('CHN', 'China');
INSERT INTO "Country" VALUES ('CXR', 'Christmas Island');
INSERT INTO "Country" VALUES ('CCK', 'Cocos Islands');
INSERT INTO "Country" VALUES ('COL', 'Colombia');
INSERT INTO "Country" VALUES ('COM', 'Comoros');
INSERT INTO "Country" VALUES ('COK', 'Cook Islands');
INSERT INTO "Country" VALUES ('CRI', 'Costa Rica');
INSERT INTO "Country" VALUES ('HRV', 'Croatia');
INSERT INTO "Country" VALUES ('CUB', 'Cuba');
INSERT INTO "Country" VALUES ('CUW', 'Curacao');
INSERT INTO "Country" VALUES ('CYP', 'Cyprus');
INSERT INTO "Country" VALUES ('CZE', 'Czech Republic');
INSERT INTO "Country" VALUES ('COD', 'Democratic Republic of the Congo');
INSERT INTO "Country" VALUES ('DNK', 'Denmark');
INSERT INTO "Country" VALUES ('DJI', 'Djibouti');
INSERT INTO "Country" VALUES ('DMA', 'Dominica');
INSERT INTO "Country" VALUES ('DOM', 'Dominican Republic');
INSERT INTO "Country" VALUES ('TLS', 'East Timor');
INSERT INTO "Country" VALUES ('ECU', 'Ecuador');
INSERT INTO "Country" VALUES ('EGY', 'Egypt');
INSERT INTO "Country" VALUES ('SLV', 'El Salvador');
INSERT INTO "Country" VALUES ('GNQ', 'Equatorial Guinea');
INSERT INTO "Country" VALUES ('ERI', 'Eritrea');
INSERT INTO "Country" VALUES ('EST', 'Estonia');
INSERT INTO "Country" VALUES ('ETH', 'Ethiopia');
INSERT INTO "Country" VALUES ('FLK', 'Falkland Islands');
INSERT INTO "Country" VALUES ('FRO', 'Faroe Islands');
INSERT INTO "Country" VALUES ('FJI', 'Fiji');
INSERT INTO "Country" VALUES ('FIN', 'Finland');
INSERT INTO "Country" VALUES ('FRA', 'France');
INSERT INTO "Country" VALUES ('PYF', 'French Polynesia');
INSERT INTO "Country" VALUES ('GAB', 'Gabon');
INSERT INTO "Country" VALUES ('GMB', 'Gambia');
INSERT INTO "Country" VALUES ('GEO', 'Georgia');
INSERT INTO "Country" VALUES ('DEU', 'Germany');
INSERT INTO "Country" VALUES ('GHA', 'Ghana');
INSERT INTO "Country" VALUES ('GIB', 'Gibraltar');
INSERT INTO "Country" VALUES ('GRC', 'Greece');
INSERT INTO "Country" VALUES ('GRL', 'Greenland');
INSERT INTO "Country" VALUES ('GRD', 'Grenada');
INSERT INTO "Country" VALUES ('GUM', 'Guam');
INSERT INTO "Country" VALUES ('GTM', 'Guatemala');
INSERT INTO "Country" VALUES ('GGY', 'Guernsey');
INSERT INTO "Country" VALUES ('GIN', 'Guinea');
INSERT INTO "Country" VALUES ('GNB', 'Guinea-Bissau');
INSERT INTO "Country" VALUES ('GUY', 'Guyana');
INSERT INTO "Country" VALUES ('HTI', 'Haiti');
INSERT INTO "Country" VALUES ('HND', 'Honduras');
INSERT INTO "Country" VALUES ('HKG', 'Hong Kong');
INSERT INTO "Country" VALUES ('HUN', 'Hungary');
INSERT INTO "Country" VALUES ('ISL', 'Iceland');
INSERT INTO "Country" VALUES ('IND', 'India');
INSERT INTO "Country" VALUES ('IDN', 'Indonesia');
INSERT INTO "Country" VALUES ('IRN', 'Iran');
INSERT INTO "Country" VALUES ('IRQ', 'Iraq');
INSERT INTO "Country" VALUES ('IRL', 'Ireland');
INSERT INTO "Country" VALUES ('IMN', 'Isle of Man');
INSERT INTO "Country" VALUES ('ISR', 'Israel');
INSERT INTO "Country" VALUES ('ITA', 'Italy');
INSERT INTO "Country" VALUES ('CIV', 'Ivory Coast');
INSERT INTO "Country" VALUES ('JAM', 'Jamaica');
INSERT INTO "Country" VALUES ('JPN', 'Japan');
INSERT INTO "Country" VALUES ('JEY', 'Jersey');
INSERT INTO "Country" VALUES ('JOR', 'Jordan');
INSERT INTO "Country" VALUES ('KAZ', 'Kazakhstan');
INSERT INTO "Country" VALUES ('KEN', 'Kenya');
INSERT INTO "Country" VALUES ('KIR', 'Kiribati');
INSERT INTO "Country" VALUES ('XKX', 'Kosovo');
INSERT INTO "Country" VALUES ('KWT', 'Kuwait');
INSERT INTO "Country" VALUES ('KGZ', 'Kyrgyzstan');
INSERT INTO "Country" VALUES ('LAO', 'Laos');
INSERT INTO "Country" VALUES ('LVA', 'Latvia');
INSERT INTO "Country" VALUES ('LBN', 'Lebanon');
INSERT INTO "Country" VALUES ('LSO', 'Lesotho');
INSERT INTO "Country" VALUES ('LBR', 'Liberia');
INSERT INTO "Country" VALUES ('LBY', 'Libya');
INSERT INTO "Country" VALUES ('LIE', 'Liechtenstein');
INSERT INTO "Country" VALUES ('LTU', 'Lithuania');
INSERT INTO "Country" VALUES ('LUX', 'Luxembourg');
INSERT INTO "Country" VALUES ('MAC', 'Macau');
INSERT INTO "Country" VALUES ('MKD', 'Macedonia');
INSERT INTO "Country" VALUES ('MDG', 'Madagascar');
INSERT INTO "Country" VALUES ('MWI', 'Malawi');
INSERT INTO "Country" VALUES ('MYS', 'Malaysia');
INSERT INTO "Country" VALUES ('MDV', 'Maldives');
INSERT INTO "Country" VALUES ('MLI', 'Mali');
INSERT INTO "Country" VALUES ('MLT', 'Malta');
INSERT INTO "Country" VALUES ('MHL', 'Marshall Islands');
INSERT INTO "Country" VALUES ('MRT', 'Mauritania');
INSERT INTO "Country" VALUES ('MUS', 'Mauritius');
INSERT INTO "Country" VALUES ('MYT', 'Mayotte');
INSERT INTO "Country" VALUES ('MEX', 'Mexico');
INSERT INTO "Country" VALUES ('FSM', 'Micronesia');
INSERT INTO "Country" VALUES ('MDA', 'Moldova');
INSERT INTO "Country" VALUES ('MCO', 'Monaco');
INSERT INTO "Country" VALUES ('MNG', 'Mongolia');
INSERT INTO "Country" VALUES ('MNE', 'Montenegro');
INSERT INTO "Country" VALUES ('MSR', 'Montserrat');
INSERT INTO "Country" VALUES ('MAR', 'Morocco');
INSERT INTO "Country" VALUES ('MOZ', 'Mozambique');
INSERT INTO "Country" VALUES ('MMR', 'Myanmar');
INSERT INTO "Country" VALUES ('NAM', 'Namibia');
INSERT INTO "Country" VALUES ('NRU', 'Nauru');
INSERT INTO "Country" VALUES ('NPL', 'Nepal');
INSERT INTO "Country" VALUES ('NLD', 'Netherlands');
INSERT INTO "Country" VALUES ('ANT', 'Netherlands Antilles');
INSERT INTO "Country" VALUES ('NCL', 'New Caledonia');
INSERT INTO "Country" VALUES ('NZL', 'New Zealand');
INSERT INTO "Country" VALUES ('NIC', 'Nicaragua');
INSERT INTO "Country" VALUES ('NER', 'Niger');
INSERT INTO "Country" VALUES ('NGA', 'Nigeria');
INSERT INTO "Country" VALUES ('NIU', 'Niue');
INSERT INTO "Country" VALUES ('PRK', 'North Korea');
INSERT INTO "Country" VALUES ('MNP', 'Northern Mariana Islands');
INSERT INTO "Country" VALUES ('NOR', 'Norway');
INSERT INTO "Country" VALUES ('OMN', 'Oman');
INSERT INTO "Country" VALUES ('PAK', 'Pakistan');
INSERT INTO "Country" VALUES ('PLW', 'Palau');
INSERT INTO "Country" VALUES ('PSE', 'Palestine');
INSERT INTO "Country" VALUES ('PAN', 'Panama');
INSERT INTO "Country" VALUES ('PNG', 'Papua New Guinea');
INSERT INTO "Country" VALUES ('PRY', 'Paraguay');
INSERT INTO "Country" VALUES ('PER', 'Peru');
INSERT INTO "Country" VALUES ('PHL', 'Philippines');
INSERT INTO "Country" VALUES ('PCN', 'Pitcairn');
INSERT INTO "Country" VALUES ('POL', 'Poland');
INSERT INTO "Country" VALUES ('PRT', 'Portugal');
INSERT INTO "Country" VALUES ('PRI', 'Puerto Rico');
INSERT INTO "Country" VALUES ('QAT', 'Qatar');
INSERT INTO "Country" VALUES ('COG', 'Republic of the Congo');
INSERT INTO "Country" VALUES ('REU', 'Reunion');
INSERT INTO "Country" VALUES ('ROU', 'Romania');
INSERT INTO "Country" VALUES ('RUS', 'Russia');
INSERT INTO "Country" VALUES ('RWA', 'Rwanda');
INSERT INTO "Country" VALUES ('BLM', 'Saint Barthelemy');
INSERT INTO "Country" VALUES ('SHN', 'Saint Helena');
INSERT INTO "Country" VALUES ('KNA', 'Saint Kitts and Nevis');
INSERT INTO "Country" VALUES ('LCA', 'Saint Lucia');
INSERT INTO "Country" VALUES ('MAF', 'Saint Martin');
INSERT INTO "Country" VALUES ('SPM', 'Saint Pierre and Miquelon');
INSERT INTO "Country" VALUES ('VCT', 'Saint Vincent and the Grenadines');
INSERT INTO "Country" VALUES ('WSM', 'Samoa');
INSERT INTO "Country" VALUES ('SMR', 'San Marino');
INSERT INTO "Country" VALUES ('STP', 'Sao Tome and Principe');
INSERT INTO "Country" VALUES ('SAU', 'Saudi Arabia');
INSERT INTO "Country" VALUES ('SEN', 'Senegal');
INSERT INTO "Country" VALUES ('SRB', 'Serbia');
INSERT INTO "Country" VALUES ('SYC', 'Seychelles');
INSERT INTO "Country" VALUES ('SLE', 'Sierra Leone');
INSERT INTO "Country" VALUES ('SGP', 'Singapore');
INSERT INTO "Country" VALUES ('SXM', 'Sint Maarten');
INSERT INTO "Country" VALUES ('SVK', 'Slovakia');
INSERT INTO "Country" VALUES ('SVN', 'Slovenia');
INSERT INTO "Country" VALUES ('SLB', 'Solomon Islands');
INSERT INTO "Country" VALUES ('SOM', 'Somalia');
INSERT INTO "Country" VALUES ('ZAF', 'South Africa');
INSERT INTO "Country" VALUES ('KOR', 'South Korea');
INSERT INTO "Country" VALUES ('SSD', 'South Sudan');
INSERT INTO "Country" VALUES ('ESP', 'Spain');
INSERT INTO "Country" VALUES ('LKA', 'Sri Lanka');
INSERT INTO "Country" VALUES ('SDN', 'Sudan');
INSERT INTO "Country" VALUES ('SUR', 'Suriname');
INSERT INTO "Country" VALUES ('SJM', 'Svalbard and Jan Mayen');
INSERT INTO "Country" VALUES ('SWZ', 'Swaziland');
INSERT INTO "Country" VALUES ('SWE', 'Sweden');
INSERT INTO "Country" VALUES ('CHE', 'Switzerland');
INSERT INTO "Country" VALUES ('SYR', 'Syria');
INSERT INTO "Country" VALUES ('TWN', 'Taiwan');
INSERT INTO "Country" VALUES ('TJK', 'Tajikistan');
INSERT INTO "Country" VALUES ('TZA', 'Tanzania');
INSERT INTO "Country" VALUES ('THA', 'Thailand');
INSERT INTO "Country" VALUES ('TGO', 'Togo');
INSERT INTO "Country" VALUES ('TKL', 'Tokelau');
INSERT INTO "Country" VALUES ('TON', 'Tonga');
INSERT INTO "Country" VALUES ('TTO', 'Trinidad and Tobago');
INSERT INTO "Country" VALUES ('TUN', 'Tunisia');
INSERT INTO "Country" VALUES ('TUR', 'Turkey');
INSERT INTO "Country" VALUES ('TKM', 'Turkmenistan');
INSERT INTO "Country" VALUES ('TCA', 'Turks and Caicos Islands');
INSERT INTO "Country" VALUES ('TUV', 'Tuvalu');
INSERT INTO "Country" VALUES ('VIR', 'U.S. Virgin Islands');
INSERT INTO "Country" VALUES ('UGA', 'Uganda');
INSERT INTO "Country" VALUES ('UKR', 'Ukraine');
INSERT INTO "Country" VALUES ('ARE', 'United Arab Emirates');
INSERT INTO "Country" VALUES ('GBR', 'United Kingdom');
INSERT INTO "Country" VALUES ('USA', 'United States');
INSERT INTO "Country" VALUES ('URY', 'Uruguay');
INSERT INTO "Country" VALUES ('UZB', 'Uzbekistan');
INSERT INTO "Country" VALUES ('VUT', 'Vanuatu');
INSERT INTO "Country" VALUES ('VAT', 'Vatican');
INSERT INTO "Country" VALUES ('VEN', 'Venezuela');
INSERT INTO "Country" VALUES ('VNM', 'Vietnam');
INSERT INTO "Country" VALUES ('WLF', 'Wallis and Futuna');
INSERT INTO "Country" VALUES ('ESH', 'Western Sahara');
INSERT INTO "Country" VALUES ('YEM', 'Yemen');
INSERT INTO "Country" VALUES ('ZMB', 'Zambia');
INSERT INTO "Country" VALUES ('ZWE', 'Zimbabwe');

-- Query = 'Singapore'
SELECT "countryName" FROM "Country" WHERE "countryCode" = 'SGP';

-- COUNT = 240
SELECT COUNT(1) FROM "Country"; 
