DELETE FROM Country WHERE 1=1;

INSERT INTO Country(countryCode, countryName) VALUES ('AFG', 'Afghanistan');
INSERT INTO Country(countryCode, countryName) VALUES ('ALB', 'Albania');
INSERT INTO Country(countryCode, countryName) VALUES ('DZA', 'Algeria');
INSERT INTO Country(countryCode, countryName) VALUES ('ASM', 'American Samoa');
INSERT INTO Country(countryCode, countryName) VALUES ('AND', 'Andorra');
INSERT INTO Country(countryCode, countryName) VALUES ('AGO', 'Angola');
INSERT INTO Country(countryCode, countryName) VALUES ('AIA', 'Anguilla');
INSERT INTO Country(countryCode, countryName) VALUES ('ATA', 'Antarctica');
INSERT INTO Country(countryCode, countryName) VALUES ('ATG', 'Antigua and Barbuda');
INSERT INTO Country(countryCode, countryName) VALUES ('ARG', 'Argentina');
INSERT INTO Country(countryCode, countryName) VALUES ('ARM', 'Armenia');
INSERT INTO Country(countryCode, countryName) VALUES ('ABW', 'Aruba');
INSERT INTO Country(countryCode, countryName) VALUES ('AUS', 'Australia');
INSERT INTO Country(countryCode, countryName) VALUES ('AUT', 'Austria');
INSERT INTO Country(countryCode, countryName) VALUES ('AZE', 'Azerbaijan');
INSERT INTO Country(countryCode, countryName) VALUES ('BHS', 'Bahamas');
INSERT INTO Country(countryCode, countryName) VALUES ('BHR', 'Bahrain');
INSERT INTO Country(countryCode, countryName) VALUES ('BGD', 'Bangladesh');
INSERT INTO Country(countryCode, countryName) VALUES ('BRB', 'Barbados');
INSERT INTO Country(countryCode, countryName) VALUES ('BLR', 'Belarus');
INSERT INTO Country(countryCode, countryName) VALUES ('BEL', 'Belgium');
INSERT INTO Country(countryCode, countryName) VALUES ('BLZ', 'Belize');
INSERT INTO Country(countryCode, countryName) VALUES ('BEN', 'Benin');
INSERT INTO Country(countryCode, countryName) VALUES ('BMU', 'Bermuda');
INSERT INTO Country(countryCode, countryName) VALUES ('BTN', 'Bhutan');
INSERT INTO Country(countryCode, countryName) VALUES ('BOL', 'Bolivia');
INSERT INTO Country(countryCode, countryName) VALUES ('BIH', 'Bosnia and Herzegovina');
INSERT INTO Country(countryCode, countryName) VALUES ('BWA', 'Botswana');
INSERT INTO Country(countryCode, countryName) VALUES ('BRA', 'Brazil');
INSERT INTO Country(countryCode, countryName) VALUES ('IOT', 'British Indian Ocean Territory');
INSERT INTO Country(countryCode, countryName) VALUES ('VGB', 'British Virgin Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('BRN', 'Brunei');
INSERT INTO Country(countryCode, countryName) VALUES ('BGR', 'Bulgaria');
INSERT INTO Country(countryCode, countryName) VALUES ('BFA', 'Burkina Faso');
INSERT INTO Country(countryCode, countryName) VALUES ('BDI', 'Burundi');
INSERT INTO Country(countryCode, countryName) VALUES ('KHM', 'Cambodia');
INSERT INTO Country(countryCode, countryName) VALUES ('CMR', 'Cameroon');
INSERT INTO Country(countryCode, countryName) VALUES ('CAN', 'Canada');
INSERT INTO Country(countryCode, countryName) VALUES ('CPV', 'Cape Verde');
INSERT INTO Country(countryCode, countryName) VALUES ('CYM', 'Cayman Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('CAF', 'Central African Republic');
INSERT INTO Country(countryCode, countryName) VALUES ('TCD', 'Chad');
INSERT INTO Country(countryCode, countryName) VALUES ('CHL', 'Chile');
INSERT INTO Country(countryCode, countryName) VALUES ('CHN', 'China');
INSERT INTO Country(countryCode, countryName) VALUES ('CXR', 'Christmas Island');
INSERT INTO Country(countryCode, countryName) VALUES ('CCK', 'Cocos Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('COL', 'Colombia');
INSERT INTO Country(countryCode, countryName) VALUES ('COM', 'Comoros');
INSERT INTO Country(countryCode, countryName) VALUES ('COK', 'Cook Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('CRI', 'Costa Rica');
INSERT INTO Country(countryCode, countryName) VALUES ('HRV', 'Croatia');
INSERT INTO Country(countryCode, countryName) VALUES ('CUB', 'Cuba');
INSERT INTO Country(countryCode, countryName) VALUES ('CUW', 'Curacao');
INSERT INTO Country(countryCode, countryName) VALUES ('CYP', 'Cyprus');
INSERT INTO Country(countryCode, countryName) VALUES ('CZE', 'Czech Republic');
INSERT INTO Country(countryCode, countryName) VALUES ('COD', 'Democratic Republic of the Congo');
INSERT INTO Country(countryCode, countryName) VALUES ('DNK', 'Denmark');
INSERT INTO Country(countryCode, countryName) VALUES ('DJI', 'Djibouti');
INSERT INTO Country(countryCode, countryName) VALUES ('DMA', 'Dominica');
INSERT INTO Country(countryCode, countryName) VALUES ('DOM', 'Dominican Republic');
INSERT INTO Country(countryCode, countryName) VALUES ('TLS', 'East Timor');
INSERT INTO Country(countryCode, countryName) VALUES ('ECU', 'Ecuador');
INSERT INTO Country(countryCode, countryName) VALUES ('EGY', 'Egypt');
INSERT INTO Country(countryCode, countryName) VALUES ('SLV', 'El Salvador');
INSERT INTO Country(countryCode, countryName) VALUES ('GNQ', 'Equatorial Guinea');
INSERT INTO Country(countryCode, countryName) VALUES ('ERI', 'Eritrea');
INSERT INTO Country(countryCode, countryName) VALUES ('EST', 'Estonia');
INSERT INTO Country(countryCode, countryName) VALUES ('ETH', 'Ethiopia');
INSERT INTO Country(countryCode, countryName) VALUES ('FLK', 'Falkland Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('FRO', 'Faroe Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('FJI', 'Fiji');
INSERT INTO Country(countryCode, countryName) VALUES ('FIN', 'Finland');
INSERT INTO Country(countryCode, countryName) VALUES ('FRA', 'France');
INSERT INTO Country(countryCode, countryName) VALUES ('PYF', 'French Polynesia');
INSERT INTO Country(countryCode, countryName) VALUES ('GAB', 'Gabon');
INSERT INTO Country(countryCode, countryName) VALUES ('GMB', 'Gambia');
INSERT INTO Country(countryCode, countryName) VALUES ('GEO', 'Georgia');
INSERT INTO Country(countryCode, countryName) VALUES ('DEU', 'Germany');
INSERT INTO Country(countryCode, countryName) VALUES ('GHA', 'Ghana');
INSERT INTO Country(countryCode, countryName) VALUES ('GIB', 'Gibraltar');
INSERT INTO Country(countryCode, countryName) VALUES ('GRC', 'Greece');
INSERT INTO Country(countryCode, countryName) VALUES ('GRL', 'Greenland');
INSERT INTO Country(countryCode, countryName) VALUES ('GRD', 'Grenada');
INSERT INTO Country(countryCode, countryName) VALUES ('GUM', 'Guam');
INSERT INTO Country(countryCode, countryName) VALUES ('GTM', 'Guatemala');
INSERT INTO Country(countryCode, countryName) VALUES ('GGY', 'Guernsey');
INSERT INTO Country(countryCode, countryName) VALUES ('GIN', 'Guinea');
INSERT INTO Country(countryCode, countryName) VALUES ('GNB', 'Guinea-Bissau');
INSERT INTO Country(countryCode, countryName) VALUES ('GUY', 'Guyana');
INSERT INTO Country(countryCode, countryName) VALUES ('HTI', 'Haiti');
INSERT INTO Country(countryCode, countryName) VALUES ('HND', 'Honduras');
INSERT INTO Country(countryCode, countryName) VALUES ('HKG', 'Hong Kong');
INSERT INTO Country(countryCode, countryName) VALUES ('HUN', 'Hungary');
INSERT INTO Country(countryCode, countryName) VALUES ('ISL', 'Iceland');
INSERT INTO Country(countryCode, countryName) VALUES ('IND', 'India');
INSERT INTO Country(countryCode, countryName) VALUES ('IDN', 'Indonesia');
INSERT INTO Country(countryCode, countryName) VALUES ('IRN', 'Iran');
INSERT INTO Country(countryCode, countryName) VALUES ('IRQ', 'Iraq');
INSERT INTO Country(countryCode, countryName) VALUES ('IRL', 'Ireland');
INSERT INTO Country(countryCode, countryName) VALUES ('IMN', 'Isle of Man');
INSERT INTO Country(countryCode, countryName) VALUES ('ISR', 'Israel');
INSERT INTO Country(countryCode, countryName) VALUES ('ITA', 'Italy');
INSERT INTO Country(countryCode, countryName) VALUES ('CIV', 'Ivory Coast');
INSERT INTO Country(countryCode, countryName) VALUES ('JAM', 'Jamaica');
INSERT INTO Country(countryCode, countryName) VALUES ('JPN', 'Japan');
INSERT INTO Country(countryCode, countryName) VALUES ('JEY', 'Jersey');
INSERT INTO Country(countryCode, countryName) VALUES ('JOR', 'Jordan');
INSERT INTO Country(countryCode, countryName) VALUES ('KAZ', 'Kazakhstan');
INSERT INTO Country(countryCode, countryName) VALUES ('KEN', 'Kenya');
INSERT INTO Country(countryCode, countryName) VALUES ('KIR', 'Kiribati');
INSERT INTO Country(countryCode, countryName) VALUES ('XKX', 'Kosovo');
INSERT INTO Country(countryCode, countryName) VALUES ('KWT', 'Kuwait');
INSERT INTO Country(countryCode, countryName) VALUES ('KGZ', 'Kyrgyzstan');
INSERT INTO Country(countryCode, countryName) VALUES ('LAO', 'Laos');
INSERT INTO Country(countryCode, countryName) VALUES ('LVA', 'Latvia');
INSERT INTO Country(countryCode, countryName) VALUES ('LBN', 'Lebanon');
INSERT INTO Country(countryCode, countryName) VALUES ('LSO', 'Lesotho');
INSERT INTO Country(countryCode, countryName) VALUES ('LBR', 'Liberia');
INSERT INTO Country(countryCode, countryName) VALUES ('LBY', 'Libya');
INSERT INTO Country(countryCode, countryName) VALUES ('LIE', 'Liechtenstein');
INSERT INTO Country(countryCode, countryName) VALUES ('LTU', 'Lithuania');
INSERT INTO Country(countryCode, countryName) VALUES ('LUX', 'Luxembourg');
INSERT INTO Country(countryCode, countryName) VALUES ('MAC', 'Macau');
INSERT INTO Country(countryCode, countryName) VALUES ('MKD', 'Macedonia');
INSERT INTO Country(countryCode, countryName) VALUES ('MDG', 'Madagascar');
INSERT INTO Country(countryCode, countryName) VALUES ('MWI', 'Malawi');
INSERT INTO Country(countryCode, countryName) VALUES ('MYS', 'Malaysia');
INSERT INTO Country(countryCode, countryName) VALUES ('MDV', 'Maldives');
INSERT INTO Country(countryCode, countryName) VALUES ('MLI', 'Mali');
INSERT INTO Country(countryCode, countryName) VALUES ('MLT', 'Malta');
INSERT INTO Country(countryCode, countryName) VALUES ('MHL', 'Marshall Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('MRT', 'Mauritania');
INSERT INTO Country(countryCode, countryName) VALUES ('MUS', 'Mauritius');
INSERT INTO Country(countryCode, countryName) VALUES ('MYT', 'Mayotte');
INSERT INTO Country(countryCode, countryName) VALUES ('MEX', 'Mexico');
INSERT INTO Country(countryCode, countryName) VALUES ('FSM', 'Micronesia');
INSERT INTO Country(countryCode, countryName) VALUES ('MDA', 'Moldova');
INSERT INTO Country(countryCode, countryName) VALUES ('MCO', 'Monaco');
INSERT INTO Country(countryCode, countryName) VALUES ('MNG', 'Mongolia');
INSERT INTO Country(countryCode, countryName) VALUES ('MNE', 'Montenegro');
INSERT INTO Country(countryCode, countryName) VALUES ('MSR', 'Montserrat');
INSERT INTO Country(countryCode, countryName) VALUES ('MAR', 'Morocco');
INSERT INTO Country(countryCode, countryName) VALUES ('MOZ', 'Mozambique');
INSERT INTO Country(countryCode, countryName) VALUES ('MMR', 'Myanmar');
INSERT INTO Country(countryCode, countryName) VALUES ('NAM', 'Namibia');
INSERT INTO Country(countryCode, countryName) VALUES ('NRU', 'Nauru');
INSERT INTO Country(countryCode, countryName) VALUES ('NPL', 'Nepal');
INSERT INTO Country(countryCode, countryName) VALUES ('NLD', 'Netherlands');
INSERT INTO Country(countryCode, countryName) VALUES ('ANT', 'Netherlands Antilles');
INSERT INTO Country(countryCode, countryName) VALUES ('NCL', 'New Caledonia');
INSERT INTO Country(countryCode, countryName) VALUES ('NZL', 'New Zealand');
INSERT INTO Country(countryCode, countryName) VALUES ('NIC', 'Nicaragua');
INSERT INTO Country(countryCode, countryName) VALUES ('NER', 'Niger');
INSERT INTO Country(countryCode, countryName) VALUES ('NGA', 'Nigeria');
INSERT INTO Country(countryCode, countryName) VALUES ('NIU', 'Niue');
INSERT INTO Country(countryCode, countryName) VALUES ('PRK', 'North Korea');
INSERT INTO Country(countryCode, countryName) VALUES ('MNP', 'Northern Mariana Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('NOR', 'Norway');
INSERT INTO Country(countryCode, countryName) VALUES ('OMN', 'Oman');
INSERT INTO Country(countryCode, countryName) VALUES ('PAK', 'Pakistan');
INSERT INTO Country(countryCode, countryName) VALUES ('PLW', 'Palau');
INSERT INTO Country(countryCode, countryName) VALUES ('PSE', 'Palestine');
INSERT INTO Country(countryCode, countryName) VALUES ('PAN', 'Panama');
INSERT INTO Country(countryCode, countryName) VALUES ('PNG', 'Papua New Guinea');
INSERT INTO Country(countryCode, countryName) VALUES ('PRY', 'Paraguay');
INSERT INTO Country(countryCode, countryName) VALUES ('PER', 'Peru');
INSERT INTO Country(countryCode, countryName) VALUES ('PHL', 'Philippines');
INSERT INTO Country(countryCode, countryName) VALUES ('PCN', 'Pitcairn');
INSERT INTO Country(countryCode, countryName) VALUES ('POL', 'Poland');
INSERT INTO Country(countryCode, countryName) VALUES ('PRT', 'Portugal');
INSERT INTO Country(countryCode, countryName) VALUES ('PRI', 'Puerto Rico');
INSERT INTO Country(countryCode, countryName) VALUES ('QAT', 'Qatar');
INSERT INTO Country(countryCode, countryName) VALUES ('COG', 'Republic of the Congo');
INSERT INTO Country(countryCode, countryName) VALUES ('REU', 'Reunion');
INSERT INTO Country(countryCode, countryName) VALUES ('ROU', 'Romania');
INSERT INTO Country(countryCode, countryName) VALUES ('RUS', 'Russia');
INSERT INTO Country(countryCode, countryName) VALUES ('RWA', 'Rwanda');
INSERT INTO Country(countryCode, countryName) VALUES ('BLM', 'Saint Barthelemy');
INSERT INTO Country(countryCode, countryName) VALUES ('SHN', 'Saint Helena');
INSERT INTO Country(countryCode, countryName) VALUES ('KNA', 'Saint Kitts and Nevis');
INSERT INTO Country(countryCode, countryName) VALUES ('LCA', 'Saint Lucia');
INSERT INTO Country(countryCode, countryName) VALUES ('MAF', 'Saint Martin');
INSERT INTO Country(countryCode, countryName) VALUES ('SPM', 'Saint Pierre and Miquelon');
INSERT INTO Country(countryCode, countryName) VALUES ('VCT', 'Saint Vincent and the Grenadines');
INSERT INTO Country(countryCode, countryName) VALUES ('WSM', 'Samoa');
INSERT INTO Country(countryCode, countryName) VALUES ('SMR', 'San Marino');
INSERT INTO Country(countryCode, countryName) VALUES ('STP', 'Sao Tome and Principe');
INSERT INTO Country(countryCode, countryName) VALUES ('SAU', 'Saudi Arabia');
INSERT INTO Country(countryCode, countryName) VALUES ('SEN', 'Senegal');
INSERT INTO Country(countryCode, countryName) VALUES ('SRB', 'Serbia');
INSERT INTO Country(countryCode, countryName) VALUES ('SYC', 'Seychelles');
INSERT INTO Country(countryCode, countryName) VALUES ('SLE', 'Sierra Leone');
INSERT INTO Country(countryCode, countryName) VALUES ('SGP', 'Singapore');
INSERT INTO Country(countryCode, countryName) VALUES ('SXM', 'Sint Maarten');
INSERT INTO Country(countryCode, countryName) VALUES ('SVK', 'Slovakia');
INSERT INTO Country(countryCode, countryName) VALUES ('SVN', 'Slovenia');
INSERT INTO Country(countryCode, countryName) VALUES ('SLB', 'Solomon Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('SOM', 'Somalia');
INSERT INTO Country(countryCode, countryName) VALUES ('ZAF', 'South Africa');
INSERT INTO Country(countryCode, countryName) VALUES ('KOR', 'South Korea');
INSERT INTO Country(countryCode, countryName) VALUES ('SSD', 'South Sudan');
INSERT INTO Country(countryCode, countryName) VALUES ('ESP', 'Spain');
INSERT INTO Country(countryCode, countryName) VALUES ('LKA', 'Sri Lanka');
INSERT INTO Country(countryCode, countryName) VALUES ('SDN', 'Sudan');
INSERT INTO Country(countryCode, countryName) VALUES ('SUR', 'Suriname');
INSERT INTO Country(countryCode, countryName) VALUES ('SJM', 'Svalbard and Jan Mayen');
INSERT INTO Country(countryCode, countryName) VALUES ('SWZ', 'Swaziland');
INSERT INTO Country(countryCode, countryName) VALUES ('SWE', 'Sweden');
INSERT INTO Country(countryCode, countryName) VALUES ('CHE', 'Switzerland');
INSERT INTO Country(countryCode, countryName) VALUES ('SYR', 'Syria');
INSERT INTO Country(countryCode, countryName) VALUES ('TWN', 'Taiwan');
INSERT INTO Country(countryCode, countryName) VALUES ('TJK', 'Tajikistan');
INSERT INTO Country(countryCode, countryName) VALUES ('TZA', 'Tanzania');
INSERT INTO Country(countryCode, countryName) VALUES ('THA', 'Thailand');
INSERT INTO Country(countryCode, countryName) VALUES ('TGO', 'Togo');
INSERT INTO Country(countryCode, countryName) VALUES ('TKL', 'Tokelau');
INSERT INTO Country(countryCode, countryName) VALUES ('TON', 'Tonga');
INSERT INTO Country(countryCode, countryName) VALUES ('TTO', 'Trinidad and Tobago');
INSERT INTO Country(countryCode, countryName) VALUES ('TUN', 'Tunisia');
INSERT INTO Country(countryCode, countryName) VALUES ('TUR', 'Turkey');
INSERT INTO Country(countryCode, countryName) VALUES ('TKM', 'Turkmenistan');
INSERT INTO Country(countryCode, countryName) VALUES ('TCA', 'Turks and Caicos Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('TUV', 'Tuvalu');
INSERT INTO Country(countryCode, countryName) VALUES ('VIR', 'U.S. Virgin Islands');
INSERT INTO Country(countryCode, countryName) VALUES ('UGA', 'Uganda');
INSERT INTO Country(countryCode, countryName) VALUES ('UKR', 'Ukraine');
INSERT INTO Country(countryCode, countryName) VALUES ('ARE', 'United Arab Emirates');
INSERT INTO Country(countryCode, countryName) VALUES ('GBR', 'United Kingdom');
INSERT INTO Country(countryCode, countryName) VALUES ('USA', 'United States');
INSERT INTO Country(countryCode, countryName) VALUES ('URY', 'Uruguay');
INSERT INTO Country(countryCode, countryName) VALUES ('UZB', 'Uzbekistan');
INSERT INTO Country(countryCode, countryName) VALUES ('VUT', 'Vanuatu');
INSERT INTO Country(countryCode, countryName) VALUES ('VAT', 'Vatican');
INSERT INTO Country(countryCode, countryName) VALUES ('VEN', 'Venezuela');
INSERT INTO Country(countryCode, countryName) VALUES ('VNM', 'Vietnam');
INSERT INTO Country(countryCode, countryName) VALUES ('WLF', 'Wallis and Futuna');
INSERT INTO Country(countryCode, countryName) VALUES ('ESH', 'Western Sahara');
INSERT INTO Country(countryCode, countryName) VALUES ('YEM', 'Yemen');
INSERT INTO Country(countryCode, countryName) VALUES ('ZMB', 'Zambia');
INSERT INTO Country(countryCode, countryName) VALUES ('ZWE', 'Zimbabwe');

-- Query = 'Singapore'
SELECT countryName FROM Country WHERE countryCode = 'SGP';

-- COUNT = 240
SELECT COUNT(1) FROM Country; 
