-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;
DROP TABLE IF EXISTS CCCompany CASCADE;
DROP TABLE IF EXISTS Address CASCADE;
DROP TABLE IF EXISTS LastName CASCADE;
DROP TABLE IF EXISTS FirstName CASCADE;
DROP TABLE IF EXISTS Gender CASCADE;
DROP TABLE IF EXISTS CountryRaceStats CASCADE;
DROP TABLE IF EXISTS Race CASCADE;
DROP TABLE IF EXISTS Country CASCADE;
DROP TYPE GenderType;

CREATE TABLE Country (
	countryCode VARCHAR(3) NOT NULL,
	countryName VARCHAR(256) NOT NULL,
	PRIMARY KEY (countryCode)
);

CREATE TABLE Race (
	raceId INTEGER NOT NULL,
	raceDesc VARCHAR(256) NOT NULL,
	PRIMARY KEY (raceId)
); 

CREATE TABLE CountryRaceStats (
	countryCode VARCHAR(3) NOT NULL,
	raceId INTEGER NOT NULL,
    occurrence INTEGER NOT NULL DEFAULT 1,
	FOREIGN KEY (raceId) REFERENCES Race ON DELETE CASCADE,
	FOREIGN KEY (countryCode) REFERENCES Country ON DELETE CASCADE,
	PRIMARY KEY (countryCode, raceId)
);

CREATE TYPE GenderType AS ENUM('F', 'M');

CREATE TABLE Gender (
	gender GenderType NOT NULL,
	genderDesc VARCHAR(7) NOT NULL,
	PRIMARY KEY (gender)
);

CREATE TABLE FirstName (
	firstName VARCHAR(256) NOT NULL,
	gender GenderType NOT NULL,
	raceId INTEGER NOT NULL,
	FOREIGN KEY (raceId) REFERENCES Race ON DELETE CASCADE,
	FOREIGN KEY (gender) REFERENCES Gender ON DELETE CASCADE,
	PRIMARY KEY (firstName, gender, raceId)
);

CREATE TABLE LastName (
	lastName VARCHAR(256) NOT NULL,
	raceId INTEGER NOT NULL,
	FOREIGN KEY (raceId) REFERENCES Race ON DELETE CASCADE,
	PRIMARY KEY (lastName, raceId)
);

CREATE TABLE Address (
	postalCode VARCHAR(32) NOT NULL,
	addressDesc VARCHAR(500) NOT NULL,
	countryCode VARCHAR(3) NOT NULL, 
	FOREIGN KEY (countryCode) REFERENCES Country ON DELETE CASCADE,
	PRIMARY KEY (addressDesc)
);

CREATE TABLE CCCompany (
	companyName VARCHAR(256) NOT NULL,
	prefix INTEGER NOT NULL,
	length INTEGER NOT NULL,
	PRIMARY KEY (companyName, prefix)
);
