-- COUNTRY
DELETE FROM "Country" WHERE 1=1;
INSERT INTO "Country" VALUES ('AUS', 'Australia');
INSERT INTO "Country" VALUES ('CAN', 'Canada');
INSERT INTO "Country" VALUES ('HKG', 'Hong Kong');
INSERT INTO "Country" VALUES ('IDN', 'Indonesia');
INSERT INTO "Country" VALUES ('MYS', 'Malaysia');
INSERT INTO "Country" VALUES ('PHL', 'Philippines');
INSERT INTO "Country" VALUES ('SGP', 'Singapore');
INSERT INTO "Country" VALUES ('THA', 'Thailand');
INSERT INTO "Country" VALUES ('GBR', 'United Kingdom');
INSERT INTO "Country" VALUES ('USA', 'United States');
-- RACE
DELETE FROM "Race" WHERE 1=1;
INSERT INTO "Race" VALUES (0, 'Generic');
INSERT INTO "Race" VALUES (1, 'Chinese');
INSERT INTO "Race" VALUES (2, 'Indian');
INSERT INTO "Race" VALUES (3, 'Malay');
INSERT INTO "Race" VALUES (4, 'American');
INSERT INTO "Race" VALUES (5, 'African');
INSERT INTO "Race" VALUES (6, 'French');
-- COUNTRYRACE
DELETE FROM "CountryRace" WHERE 1=1;
INSERT INTO "CountryRace" VALUES (1, 'AUS', '4');
INSERT INTO "CountryRace" VALUES (2, 'AUS', '6');
INSERT INTO "CountryRace" VALUES (3, 'CAN', '4');
INSERT INTO "CountryRace" VALUES (4, 'CAN', '6');
INSERT INTO "CountryRace" VALUES (5, 'HKG', '1');
INSERT INTO "CountryRace" VALUES (6, 'HKG', '2');
INSERT INTO "CountryRace" VALUES (7, 'MYS', '1');
INSERT INTO "CountryRace" VALUES (8, 'MYS', '2');
INSERT INTO "CountryRace" VALUES (9, 'PHL', '3');
INSERT INTO "CountryRace" VALUES (10, 'PHL', '4');
INSERT INTO "CountryRace" VALUES (11, 'SGP', '1');
INSERT INTO "CountryRace" VALUES (12, 'SGP', '2');
INSERT INTO "CountryRace" VALUES (13, 'SGP', '3');
INSERT INTO "CountryRace" VALUES (14, 'THA', '1');
INSERT INTO "CountryRace" VALUES (15, 'THA', '3');
INSERT INTO "CountryRace" VALUES (16, 'GBR', '4');
INSERT INTO "CountryRace" VALUES (17, 'GBR', '6');
INSERT INTO "CountryRace" VALUES (18, 'USA', '4');
INSERT INTO "CountryRace" VALUES (19, 'USA', '5');
-- FIRSTNAME
DELETE FROM "FirstName" WHERE 1=1;
INSERT INTO "FirstName" VALUES (1, 'Roger', 'M', 0);
INSERT INTO "FirstName" VALUES (2, 'Rebecca', 'F', 0);
INSERT INTO "FirstName" VALUES (3, 'Linda', 'F', 0);
INSERT INTO "FirstName" VALUES (4, 'Philip', 'M', 0);
INSERT INTO "FirstName" VALUES (5, 'An', 'M', 1);
INSERT INTO "FirstName" VALUES (6, 'Bing', 'M', 1);
INSERT INTO "FirstName" VALUES (7, 'Ah lam', 'F', 1);
INSERT INTO "FirstName" VALUES (8, 'An', 'F', 1);
INSERT INTO "FirstName" VALUES (9, 'Kers', 'M', 2);
INSERT INTO "FirstName" VALUES (10, 'Mog', 'M', 2);
INSERT INTO "FirstName" VALUES (11, 'Ketaki', 'F', 2);
INSERT INTO "FirstName" VALUES (12, 'Kusum', 'F', 2);
INSERT INTO "FirstName" VALUES (13, 'Acura', 'M', 4);
INSERT INTO "FirstName" VALUES (14, 'Audio', 'M', 4);
INSERT INTO "FirstName" VALUES (15, 'Apple', 'F', 4);
INSERT INTO "FirstName" VALUES (16, 'Atlanta', 'F', 4);
INSERT INTO "FirstName" VALUES (17, 'Dume', 'M', 5);
INSERT INTO "FirstName" VALUES (18, 'Ebi', 'M', 5);
INSERT INTO "FirstName" VALUES (19, 'Cleotha', 'F', 5);
INSERT INTO "FirstName" VALUES (20, 'Deka', 'F', 5);
INSERT INTO "FirstName" VALUES (21, 'Tremeur', 'M', 6);
INSERT INTO "FirstName" VALUES (22, 'Tugdual', 'M', 6);
INSERT INTO "FirstName" VALUES (23, 'Fifine', 'F', 6);
INSERT INTO "FirstName" VALUES (24, 'Fleur', 'F', 6);
-- LASTNAME
DELETE FROM "LastName" WHERE 1=1;
INSERT INTO "LastName" VALUES (1, 'Ang', 1);
INSERT INTO "LastName" VALUES (2, 'Tan', 1);
INSERT INTO "LastName" VALUES (3, 'Balakrishnan', 2);
INSERT INTO "LastName" VALUES (4, 'Krishnamurthy', 2);
INSERT INTO "LastName" VALUES (5, 'Baltimore', 4);
INSERT INTO "LastName" VALUES (6, 'Kinderman', 4);
INSERT INTO "LastName" VALUES (7, 'Sy', 5);
INSERT INTO "LastName" VALUES (8, 'Toure', 5);
INSERT INTO "LastName" VALUES (9, 'Sayegh', 6);
INSERT INTO "LastName" VALUES (10, 'Koury', 6);
-- ADDRESS
DELETE FROM "Address" WHERE 1=1;
INSERT INTO "Address" VALUES (1, '2609', '1/44-46 Maryborough St', 'AUS');
INSERT INTO "Address" VALUES (2, '2911', 'MITCHELL', 'AUS');
INSERT INTO "Address" VALUES (3, 'T3K4T5', '62 Panorama Hills Cir NW', 'CAN');
INSERT INTO "Address" VALUES (4, 'T6G2E1', '11320 89 Ave', 'CAN');
INSERT INTO "Address" VALUES (5, '6', '26/f Modern Warehouse 6 Shing YIP Street', 'HKG');
INSERT INTO "Address" VALUES (6, '113', '113 Argyle Street', 'HKG');
INSERT INTO "Address" VALUES (7, '10130', 'Apartemen Istana Harmoni, No.2Bl G/3, Jalan Suryopranoto', 'IDN');
INSERT INTO "Address" VALUES (8, '10640', 'Ruko Mega Grosir Cempaka Mas, Lt. 2-3, Jalan Letjend Suprapto', 'IDN');
INSERT INTO "Address" VALUES (9, '43950 Sungai Pelek', 'No. 67, Jalan Pantai Bagan Lalang Kg Bagan Lalang, Bagan Lalang', 'MYS');
INSERT INTO "Address" VALUES (10, '79250 Nusajaya', 'No. 11, Ground Floor, Anjung Neighbourhood Centre, Persiaran Ledang Heights, East Ledang', 'MYS');
INSERT INTO "Address" VALUES (11, '1111', 'B-1 L-33 Gold, 54-58', 'PHL');
INSERT INTO "Address" VALUES (12, '1118', '3 Gilmore Avenue Avenue, 020', 'PHL');
INSERT INTO "Address" VALUES (13, '400848', '#01-738, 848 Sims Avenue', 'SGP');
INSERT INTO "Address" VALUES (14, '570508', '#02-384, 508 Bishan Street 11', 'SGP');
INSERT INTO "Address" VALUES (15, 'G41 3UH', '61 Ravenswood Drive', 'GBR');
INSERT INTO "Address" VALUES (16, 'DD1 1PU', '15 South Ward Road', 'GBR');
INSERT INTO "Address" VALUES (17, '10400', '296 Phayathai Rd, Khwaeng Thanon Phetchaburi, Khet Ratchathewi, Krung Thep Maha Nakhon', 'THA');
INSERT INTO "Address" VALUES (18, '10330', '831 Rama I Rd, Khwaeng Wang Mai, Khet Pathum Wan, Krung Thep Maha Nakhon', 'THA');
INSERT INTO "Address" VALUES (19, '65065', '4540 Osage Beach Pkwy P5, Osage Beach, MO', 'USA');
INSERT INTO "Address" VALUES (20, '68410', '1001 NE-2 #100, Nebraska City, NE', 'USA');
-- VERIFY
SELECT * FROM "Country";
SELECT * FROM "Race";
SELECT * FROM "CountryRace";
SELECT * FROM "FirstName";
SELECT * FROM "LastName";
SELECT * FROM "Address";